# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: juwaz
description: 'growth and resource hacker'
github_username: juwaz
# you can comment the below line out if your repo name is not different than your baseurl
github_repo: "juwaz"

# OPTIONAL: override baseurl and url if using a custom domain
# Note: leave out the trailing / from this value. 
# url: "https://juwaz" # the base hostname & protocol for your site, e.g. http://example.com

###########################################################
#########  Special Instructions for baseurl ###############
#
#### Scenario One: If you do not have a Custom Domain #####
#    -  if you are not using a custom domain, the baseurl *must* be set to your repo name
# 
####  Scenario Two: If you have a Custom Domain #####
# 1. If your domain does NOT have a subpath, this leave this value as ""
# 2. If your domain does have a subpath, you must preceed the value with a / and NOT have a / at the end.  
#      For example: 
#           "" is valid
#           "/blog"        is valid
#            "/blog/site/" is invalid  ( / at the end)
#            "/blog/site"  is valid
#            "blog/site"   is invalid  ( because doesn't begin with a /)
#
# 3. You must replace the parameter `baseurl` in _action_files/settings.ini with the same value as you set here but WITHOUT QUOTES.
#
baseurl: "" # the subpath of your site, e.g. "/blog".

# Github and twitter are optional:
minima:
  social_links:
    # twitter: juwaz
    # github: juwaz
    # source: https://github.com/jekyll/minima/blob/master/_config.yml#L18
    - { platform: twitter,         user_url: "https://twitter.com/juwazr"}
    - { platform: github,        user_url: "https://github.com/juwaz"}
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/joe-uwazurike-43191579" }
    - { platform: rss,            user_url: "/feed.xml" }
    # - { platform: devto,          user_url: "https://dev.to/jekyll" }
    # - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
    # - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
    # - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
    # - { platform: github,         user_url: "https://github.com/jekyll/minima" }
    # - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    # - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
    # - { platform: keybase,        user_url: "https://keybase.io/jekyll" }

    # - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
    # - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
    # - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
    # - { platform: telegram,       user_url: "https://t.me/jekyll" }
    # - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }
    # - {platform: linkein, user_url: "https://www.linkedin.com/in/joe-uwazurike-43191579"}

# Set this to true to get LaTeX math equation support
use_math: 

# Set this to true to display the summary of your blog post under your title on the Home page.
show_description: false

# Set this to true to display image previews on home page, if they exist
show_image: false

# Set this to true to turn on annotations with hypothes.is (https://web.hypothes.is/)
annotations: false

# Set this to true to display tags on each post
show_tags: false

# Add your Google Analytics ID here if you have one and want to use it
#google_analytics: UA-57531313-5

exclude:
  - docker-compose.yml
  - action.yml
  - Makefile

# this setting allows you to keep pages organized in the _pages folder
include:
  - _pages

# This specifies what badges are turned on by default for notebook posts.
default_badges:
  github: true
  binder: true
  colab: true
  deepnote: true

# Escape HTML in post descriptions
html_escape:
  description: false

# Everything below here should be left alone. Modifications may break fastpages
future: true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# See https://jekyllrb.com/docs/pagination/
# For pagination to work, you cannot have index.md at the root of your repo, instead you must rename this file to index.html
paginate: 15
paginate_path: /page:num/

remote_theme: jekyll/minima

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

# to limit size of xml as it can grow quite large.
feed:
  posts_limit: 5 #default posts_limit: 10
  excerpt_only: true
  
exclude:
  - settings.ini
